[workspace]
members = [
    "aerostore_core",
    "aerostore_macros",
    "aerostore_tcl",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
crossbeam = "0.8"
crossbeam-skiplist = "0.1"
